baseURL = 'https://samoyed-02.github.io/'
languageCode = 'ko-kr'
title = 'Samoyed Devlog'
theme = 'hugo-theme-stack'
paginate = 5
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  favicon = "img/favicon.png"
  mainSections = ["posts"]
  rssFullContent = true

  [params.footer]
    since = 2026
    customText = ""

  [params.dateFormat]
    published = "Jan 02, 2006"
    lastUpdated = "Jan 02, 2006 15:04"

  [params.sidebar]
    subtitle = "백엔드 개발 및 보안 기록 블로그"
    avatar = "img/avatar.jpg"

  [params.article]
    math = false
    toc = true
    readingTime = true

    [params.article.license]
      enabled = false

  [params.comments]
    enabled = false

  [[params.widgets.homepage]]
    type = "search"

  [[params.widgets.homepage]]
    type = "categories"
    [params.widgets.homepage.params]
      limit = 10

  [[params.widgets.homepage]]
    type = "archives"
    [params.widgets.homepage.params]
      limit = 5

  [[params.widgets.homepage]]
    type = "tag-cloud"
    [params.widgets.homepage.params]
      limit = 10

  [[params.widgets.page]]
    type = "toc"

  [params.colorScheme]
    toggle = true
    default = "auto"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20

  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/Samoyed-02"
    [menu.social.params]
      icon = "brand-github"
    
[[menu.main]]
    identifier = "travel"
    name = "Travel"
    url = "/travel/"
    weight = 25

[related]
  includeNewer = true
  threshold = 60
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "categories"
    weight = 200
